#!/bin/bash

set -e
source settings
here=$(pwd)
scene="$1"
obj="$2"
out="$3"
run_script="$here/make_animated_scene.py"

if [ "$#" -le 2 ]; then
  echo "Usage: $0 scene obj out" >&2
    exit 1
fi

"$blender"  "$scene" -b -P "$run_script" -- "$obj" "$out"

